services:
  aurapilot:
    build: .
    container_name: aurapilot
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - logs_data:/app/logs
    stdin_open: true
    tty: true
    environment:
    - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"

volumes:
  logs_data: